export const permission = {
  addUser: 'Add_Users',
  userList: 'View_Users',
  updateUser: 'Edit_Users',
  deleteUser: 'Delete_Users',
  bulkAddUser: 'Bulk_Add_Users',

  addRole: 'Add_Roles',
  editRole: 'Edit_Roles',
  deleteRole: 'Delete_Roles',
  roleList: 'View_Roles',

  tenantList: 'View_Tenants',
  addTenant: 'Add_Tenants',
  deleteTenant: 'Delete_Tenants',
  updateTenant: 'Edit_Tenants',

  addBusiness: 'Add_BU',
  businessList: 'View_BU',
  updateBusiness: 'Edit_BU',
  deleteBusiness: 'Delete_BU',

  addCard: 'Add_Cards',
  cardList: 'View_Cards',
  updateCard: 'Edit_Cards',
  deleteCard: 'Delete_Cards',
  courouselAddVideo: 'Courousel_Video',
  courouselAddImage: 'Courousel_Image',
  courouselAddBrochure: 'Courousel_Browcher',

  shareMyCards: 'Share_MyCards',
  myCardList: 'View_MyCards',
  updateMyCard: 'Edit_MyCards',
  previewMyCard: 'Preview_MyCards',
  scanMyCard: 'Scan_MyCards',
  addCardINWallet: 'Wallet',

  addAddress: 'Add_Address',
  addressList: 'View_Address',
  updateAddress: 'Edit_Address',
  deleteAddress: 'Delete_Address',

  addDistributor: 'Add_Distributor',
  distributorList: 'View_Distributor',
  updateDistributor: 'Edit_Distributor',
  deleteDistributor: 'Delete_Distributor',

  addReseller: 'Add_Reseller',
  resellerList: 'View_Reseller',
  updateReseller: 'Edit_Reseller',
  deleteReseller: 'Delete_Reseller',

  dashboard: 'View_Menu_Dashboard',
  role: 'View_Menu_Admin_Roles',
  user: 'View_Menu_Admin_Users',
  tenant: 'View_Menu_Tenants',
  distributor: 'View_Menu_Distributor',
  reseller: 'View_Menu_Reseller',
  cards: 'View_Menu_Cards',
  myCards: 'View_Menu_MyCards',
  businessUnit: 'View_Menu_BU',
  report: 'Reports',

  changePassword: 'Change_Password',
  address: 'View_Menu_Address',
  myConnects: "View_Menu_MyConnects",
  otherConnects: "View_Menu_OtherConnects",

  myProfile: 'My_Profile',
  editProfile: 'Edit_Profile',

  myConnectFilters: "My_Connects_Filters",
  myConnectsSearch: "My_Connects_Search",
  otherConnectFilters: "Other_Connect_Filters",
  otherConnectSearch: "Other_Connect_Search",
  approvalRequests: "Approval_Request",
  approvalLogs: "Approval_Logs",
  requestLogs: "Request_Logs",
  businessCardUsage: "Business_Cards_Usage",
  licenseUsage: "License_Usage",
  userLogin: "User_Login",
}
